### ISSUE TITLE
Track inactivity time

### ISSUE THREAD

**Issue by huntfx** [huntfx/MouseTracks#45]
The code exists to mark inactivity (to disable saving), but it could be adapted to track the time active/inactive, so it doesn't affect the overall track time, but gives more accurate stats.

**Comment by Peter92** [comment]
Done a bit of work on it and it'll count inactivity for the particular session. I'll add in an overall inactivity count, and also compensate for the threshold (eg. if threshold is 60 seconds, then after 60 seconds, remove 60 seconds from active time and add 60 seconds to inactivity time).
