### ISSUE TITLE
One important question

### ISSUE THREAD

**Issue by gamma19** [huntfx/MouseTracks#62]
How can i access the data for my mouse movements and clicks?
And when i stars generate images script it says like below:

Select a profile by typing its name or the matching ID.
Files are being sorted by "last modified - descending".
Type "sort <ID>" to change or reverse the sorting method. Possible options are Creation Time (1), File Size (2), File Version (3), Last Modified (4), Session Count (5) and Track Length (6).

Page 1 of 0. Type "page <number>" to switch.

Type your choice here: 1
Error: Invalid profile index: 1 (must be between 1-0)

**Comment by huntfx** [comment]
Hey, I know the instructions are really lacking right now, have you run the `start_tracking.py` script first to actually record the data? 
It might just be that you don't have any files saved.

**Comment by gamma19** [comment]
Yes start_tracking.py works fine but i have issue with generate_images,py.
it says select a profile but i don't know where profiles or what should i write.

**Comment by huntfx** [comment]
Could you check that you actually have ".mtk" files in "Documents/Mouse Tracks/Data"? It seems the generate images script can't find any for whatever reason.
Bear in mind the script saves on an interval of like 5 minutes or so I think, rather than constantly writing all the data, so if you've only loaded up for a minute or two at a time then that might be the issue.

**Comment by gamma19** [comment]
Hmm i think that's the issue, there is no Data folder in Mouse Tracks. Only "AppList.txt" and "settings.ini" available.

**Comment by gamma19** [comment]
And can you please tell me, how can i use colors? Like below or just Jet.
[GenerateTracks]
FileName = [[RunningTimeSeconds]]Tracks - [ColourProfile] [HighPrecision]
ColourProfile = **map.Jet.colour**

**Comment by gamma19** [comment]
Thanks for your effort it worked <3 Thanks alot!

**Comment by huntfx** [comment]
Ah glad to hear, I know things aren't particularly intuitive right now, I've got 5 years more experience though so v2 will eventually be a ton better when I get round to it :)

> And can you please tell me, how can i use colors? 

It should ask you each time you run `generate_images.py` (which you should also be able to launch if you right click the tray icon). The colours are defined in `config/colours.txt` but I think you found that already.
